" vim: set tw=0 :
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vimrc"

filetype plugin indent on
syntax on
set nocompatible
set backspace=2
set hidden
set noswapfile
set ruler
set number
set fileencoding=utf-8
set enc=utf-8
set spell
set spelllang=en,pl,ru
set laststatus=2
set path=.,**
set incsearch
"set paste
set textwidth=80 tabstop=2 shiftwidth=2 softtabstop=2 expandtab autoindent smartindent
set list
set colorcolumn=81
set nowrap
set hlsearch
set listchars+=tab:>--
set relativenumber
set wildmenu
set sidescroll=2

" check :h xterm-true-color
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
colorscheme koehler

hi ColorColumn ctermbg=red ctermfg=white
" I want my comments to be red
hi Comment ctermfg=196 ctermbg=0 guifg=red

map <C-s> <ESC>mz :w<CR><ESC>`z
imap <C-s> <ESC>mz :w<CR><ESC>`z
"imap <C-s> <ESC>mz :w<CR>`z i<RIGHT>

inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O
inoremap {})<CR> {<CR>})<ESC>O

autocmd BufNewFile  *.html 0r /Users/adam/.vim/templates/index.html
autocmd BufNewFile  *.css 0r /Users/adam/.vim/templates/style.css

" vimwiki part
let g:vimwiki_list = [{'path': '~/Documents/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]
hi vimwikiheader1 ctermbg=white ctermfg=black
hi vimwikiheader2 ctermbg=red ctermfg=black
hi vimwikiheader3 ctermbg=blue
hi vimwikiheader4 ctermbg=magenta ctermfg=black
hi vimwikiheader5 ctermbg=cyan ctermfg=black
hi vimwikiheader6 ctermbg=yellow ctermfg=black

" Load all packages in the 'start' directory
packloadall

" Settings for prettier
autocmd FileType javascript setlocal formatprg=prettier\ --single-quote\ --trailing-comma\ es5\ --arrow-parens
"autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html PrettierAsync

" Sometimes syntax highlighting can get out of sync
autocmd BufEnter *.{js,mjs} :syntax sync fromstart " this can be slow on large files
autocmd BufLeave *.{js,mjs} :syntax sync clear

" Edit the file whose name is under or after the cursor or make gf to edit a new file if does not exist already
:map gf :e <cfile><cr>

" Make the current window outstanding
hi statusline guibg=red

" Make matching parens have the same color
let g:lisp_rainbow=1
