" vim: set tw=0 :
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vimrc"

filetype plugin indent on
syntax on
set nocompatible
set backspace=2
set hidden
set noswapfile
set ruler
set number
set fileencoding=utf-8
set enc=utf-8
" http://ftp.vim.org/vim/runtime/spell/
" OR issue :set spell which should download dictionaries automatically
set spell
set spelllang=en,pl,ru
set laststatus=2
set path=.,**
set incsearch
"set paste
set textwidth=80 tabstop=2 shiftwidth=2 softtabstop=2 expandtab autoindent smartindent
set list
set colorcolumn=81
set nowrap
set hlsearch
set listchars+=tab:>--
set relativenumber
set wildmenu
set sidescroll=2

" check :h xterm-true-color
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
colorscheme koehler

hi ColorColumn ctermbg=red ctermfg=white
" I want my comments to be red
hi Comment ctermfg=196 ctermbg=0 guifg=red

inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O
inoremap {})<CR> {<CR>})<ESC>O

autocmd BufNewFile  *.html 0r $HOME/.vim/templates/index.html
autocmd BufNewFile  *.css 0r $HOME/.vim/templates/style.css

" vimwiki part
let g:vimwiki_list = [{'path': '~/Documents/vimwiki/', 'syntax': 'markdown','ext': '.md', 'auto_tags': 1}]
hi vimwikiheader1 ctermbg=white ctermfg=black
hi vimwikiheader2 ctermbg=red ctermfg=black
hi vimwikiheader3 ctermbg=blue
hi vimwikiheader4 ctermbg=magenta ctermfg=black
hi vimwikiheader5 ctermbg=cyan ctermfg=black
hi vimwikiheader6 ctermbg=yellow ctermfg=black

" Load all packages in the 'start' directory
packloadall

" Edit the file whose name is under or after the cursor or make gf to edit a new file if does not exist already
" :map gf :e <cfile><cr>
:map gf :call MyGOTOFile()<cr>

function! MyGOTOFile() abort
  let l:file = expand('<cfile>')
  " execute ':edit
  echom 'Próbujesz otworzyć ten plik: ' . l:file
  normal! gF
endfunction

" Make the current window outstanding
hi statusline guibg=red

" better indentations: do not loose focus after you indent
vnoremap < <gv
vnoremap > >gv
