let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vimrc"

filetype plugin indent on
syntax on
set nocompatible
set backspace=2
set hidden
set noswapfile
set ruler
set number
set fileencoding=utf-8
set enc=utf-8
set spell
set spelllang=en,pl
set laststatus=2
set path=.,**
set incsearch
"set paste
set textwidth=80 tabstop=4 shiftwidth=4 softtabstop=4 expandtab autoindent smartindent
set list
set colorcolumn=81
set nowrap
set hlsearch
set listchars+=tab:>--
set relativenumber
set wildmenu
set sidescroll=2

colorscheme koehler

hi ColorColumn ctermbg=red ctermfg=white
hi Comment ctermfg=196 ctermbg=0

let g:vimwiki_list = [{'path': '~/Documents/vimwiki/', 'syntax': 'markdown', 'ext': '.md'}]

map <C-s> :w<CR>
imap <C-s> <esc>:w<cr>i<right>

inoremap {<CR> {<CR>}<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

autocmd BufNewFile  *.html 0r /Users/adam/.vim/templates/index.html
autocmd BufNewFile  *.css 0r /Users/adam/.vim/templates/style.css

hi vimwikiheader1 ctermbg=red
hi vimwikiheader2 ctermbg=green
hi vimwikiheader3 ctermbg=blue
hi vimwikiheader4 ctermbg=magenta
hi vimwikiheader5 ctermbg=cyan
hi vimwikiheader6 ctermbg=yellow
